apiVersion: v1
kind: Service
metadata:
  name: lms-be-service
spec:
  selector:
    app: lms-be
  type: NodePort        # This is for minikube cluster for k8s use LoadBalancer service
  ports:
  - port: 3000          
    targetPort: 3000
    nodePort: 32100     
