apiVersion: v1
kind: Service
metadata:
  name: lms-fe-service
spec:
  type: NodePort        # This is for minikube for k8s cluster use LoadBalancer service
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32200
  selector:
    app: lms-fe
